SELECT * # CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO PARENT
JOIN ITEM_TREE ON PARENT.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
JOIN ITEM_INFO CHILD ON ITEM_TREE.ITEM_ID = CHILD.ITEM_ID;
# WHERE PARENT.RARITY = 'RARE'
# ORDER BY CHILD.ITEM_ID DESC;