# 레어를 찾는다
# (SELECT ITEM_ID 
# FROM ITEM_INFO
# WHERE RARITY = "RARE") AS RI;

SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II JOIN ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN (SELECT ITEM_ID 
                            FROM ITEM_INFO
                            WHERE RARITY = "RARE")
ORDER BY II.ITEM_ID DESC;


















# SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
# FROM ITEM_INFO
# JOIN ITEM_TREE ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
# WHERE ITEM_TREE.PARENT_ITEM_ID IN (
#     SELECT ITEM_ID
#     FROM ITEM_INFO
#     WHERE RARITY = 'RARE'
# )
# ORDER BY ITEM_INFO.ITEM_ID DESC;