# SELECT E.ID, E.GENOTYPE, PE.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA E
# LEFT JOIN ECOLI_DATA PE ON E.PARENT_ID = PE.ID
# WHERE (E.GENOYPE & PE.GENOYPE = PE.GENOYPE)
# ;

SELECT E.ID, E.GENOTYPE, PE.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E
LEFT JOIN ECOLI_DATA PE ON E.PARENT_ID = PE.ID
WHERE (E.GENOTYPE & PE.GENOTYPE) = PE.GENOTYPE
ORDER BY E.ID;
