SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, E2.YEAR_MAX - E1.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E1 JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS YEAR_MAX
    FROM ECOLI_DATA
    GROUP BY YEAR
    ) E2 ON YEAR(E1.DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;